### ISSUE TITLE
Weka exception when running with ADTree

### ISSUE THREAD

**Issue by mcchong** [fracpete/multisearch-weka-package#12]
`java weka.classifiers.meta.MultiSearch -E PRC -t train.arff -W "weka.Run weka.classifiers.trees.ADTree" -search 'weka.core.setupgenerator.MathParameter -property classifier.numOfBoostingIterations -min 5 -max 25 -step 5 -expression I' -d ADTree.model -log-file ADTree-TUNED.log`

`Weka exception: Can't find class called: weka.Run weka.classifiers.trees.ADTree
...`

Actually this might be a weka issue, since I run into a similar issue just trying to run the ADTree class in weka 3.8 (I'm using weka 3.8.0), but it blocks me from tuning with MultiSearch.

**Comment by fracpete** [comment]
I haven't tested any of the code against 3.8.0 or 3.9.0 at this stage. Have you tried running MultiSearch from within Weka's Explorer?

**Comment by mcchong** [comment]
I haven't used the explorer. Right now, I'm evaluating a set of classifiers against a set of datasets, and scripting it makes things easily reproducible for me.

**Comment by fracpete** [comment]
You can use the Explorer to generate _valid_ command-lines by configuring your classifiers/filters/etc and then copy/pasting these setups into your scripts/console. Then you only need to add the "java ..." bits and the dataset. Makes life much, much easier with nested setups, as it will get the quoting/escaping right.

**Comment by fracpete** [comment]
ADTree jars apparently not in CLASSPATH.
