### ISSUE TITLE
LibSVM weight parameter requires a blank-separated list.

### ISSUE THREAD

**Issue by mcchong** [fracpete/multisearch-weka-package#13]
It is not intuitive (or possible?) to tune parameters that require blank-separated lists as input (maybe allow specifying list separators?).  Also, the escaping situation is godawful.

`java weka.classifiers.meta.MultiSearch -E PRC -t train.arff -W weka.classifiers.functions.LibSVM -search 'weka.core.setupgenerator.MathParameter -property classifier.cost -min -3 -max 2 -step 1.0 -base 10.0 -expression "pow(BASE, I)"' -search 'weka.core.setupgenerator.MathParameter -property classifier.gamma -min -2 -max 2 -step 1.0 -base 10.0 -expression "pow(BASE, I)"' -search 'weka.core.setupgenerator.ListParameter -property classifier.weights -list "\"1 100\" \"1 10\" \"1 1\""' -d LibSVM.model -log-file LibSVM-TUNED.log`

`Zero Weights processed. Default weights will be used`

Which doesn't sound like what I want.  Can't really figure out how I should quote/not quote things to make it work...

**Comment by fracpete** [comment]
Feature got added in release [2016.4.30](https://github.com/fracpete/multisearch-weka-package/releases/tag/v2016.4.30)
