### ISSUE TITLE
Add code samples

### ISSUE THREAD

**Issue by cmmp** [fracpete/multisearch-weka-package#14]
This package is one of the most useful things there is for Weka.

However, I'm having to do quite a bit of guesswork on how to use it properly in code, because there are 0 examples.

I'm going on mostly based on the little info there is at https://weka.wikispaces.com/Optimizing+parameters#MultiSearch and my own trial and error.

Be great if there were code samples loading iris and doing some parameters search for a decision tree or some simple classifier that takes multiple parameters.

**Comment by cmmp** [comment]
I've created a sample Maven project that has code to run the multisearch.

It's hosted here: https://github.com/cmmp/multisearchtest

The example file is here: https://github.com/cmmp/multisearchtest/blob/master/src/main/java/multisearchtest/MultisearchTest.java

Maybe that could be added to your README.md or improved and then added...

**Comment by fracpete** [comment]
I never use the package from code, as I use it in the [ADAMS](https://adams.cms.waikato.ac.nz/) workflow environment through the GUI.
But since it is a good idea, I added some example code in a new repository:
https://github.com/fracpete/multisearch-weka-package-examples

**Comment by cmmp** [comment]
Thank you!
