### ISSUE TITLE
Optimizing metrics on a specific class

### ISSUE THREAD

**Issue by mcchong** [fracpete/multisearch-weka-package#18]
Hi, I'm wondering if it is possible to optimize a metric (eg. F1) for a specific class.  From what I understand, by default we're optimizing for the mean F1 over all classes.

Thanks for your help, this has been a very useful package!

**Comment by fracpete** [comment]
Per class statistics are not available at this stage. I might add that in the future, though.

**Comment by fracpete** [comment]
BTW FMEASURE used the first class label by default (the same with all class-based metrics, like precision or recall). You have to use FMEASURE_WEIGHTED for all classes.

**Comment by fracpete** [comment]
With the **2016.6.6** release, you can now specify what class label is to be optimized: use `-class-label` option in the `MultiSearch` classifier.
