### ISSUE TITLE
how to get the information about the best selected values of tuned parameters?

### ISSUE THREAD

**Issue by terry07** [fracpete/multisearch-weka-package#20]
Hello there,

i am using MultiSearch package so as to tune a Neural Network. I am using two times the ListParameters option and i am placing there the values of corresponding parameters so as to select the best ones. However, running Weka through API, i do not obtain the information about the selected combination of values but only the Accuracy value and the Confusion matrix.
Does any option exist about this request?

Thanks in advance.

**Comment by fracpete** [comment]
Have you had a look at the example repo? For example:
https://github.com/fracpete/multisearch-weka-package-examples/blob/master/src/main/java/com/github/fracpete/multisearch/optimize/J48ConfidenceFactor.java

**Comment by fracpete** [comment]
Closed due to inactivity.
