### ISSUE TITLE
Incorrect debug output when evaluating using a test set instead of a k-fold CV

### ISSUE THREAD

**Issue by eibe** [fracpete/multisearch-weka-package#27]
When specifying a test set, the debug output says that 2-fold CV is used:

...
=== Initial space - Start ===
Determining best values with 2-fold CV in space:
...

I checked the code and the corresponding if statement generating this output does not check whether a test set has been specified.

**Comment by fracpete** [comment]
Fixed with commit 2cdddd0be599d2b306cf9c609905b7836384a6a4
