### ISSUE TITLE
Add new test method using hold-out data set

### ISSUE THREAD

**Issue by krkhnh** [fracpete/multisearch-weka-package#7]
Currently, cross-validation is the only way to evaluate parameter using `multisearch`. But there are some situations that data order should be preserved. Time-related reserches like 'stock market prediction' or 'sale prediction' are such cases in my opinion. We should not use future data to estimate past, after all.

Can I request for a new feature to use hold-out data set for evaluation?

BTW, I'm not good at writing English. Sorry if I missed some manners.

**Comment by fracpete** [comment]
Added parameters to supply tests sets for initial and subsequent search space evaluation. Supplying a test set will override cross-validation.
This is available in the new [2016.1.30 release](https://github.com/fracpete/multisearch-weka-package/releases/tag/v2016.1.30).

**Comment by krkhnh** [comment]
Thank you. But I can't find the parameter from GUI. Which one is it?

![clipboard01](https://cloud.githubusercontent.com/assets/5172480/12802460/5fe03d4a-cb26-11e5-86aa-778dabca3388.png)

**Comment by fracpete** [comment]
I just downloaded the 2016.1.30 release and installed it through the Package manager. Here is what it looks like for me:
![goe](https://cloud.githubusercontent.com/assets/1026180/12802816/696c2a94-cb4a-11e5-81a0-6324f813254d.png)
Did you uninstall the old package?

**Comment by krkhnh** [comment]
Thank you. Somehow, Package manager couldn't remove the old package. So I removed it manually and it works.

**Comment by fracpete** [comment]
Unfortunately, Windows has this annoying file locking mechanism when files are being accessed. Once classes have been loaded into the JVM, they get locked AFAIK. That's why removal of packages on Windows may not always work.
