### ISSUE TITLE
Maven dependency

### ISSUE THREAD

**Issue by ghost** [fracpete/multisearch-weka-package#9]
Hi,

I'm having an issue with adding the dependency to pom.xml. 
Where exactly do I need to add this? 

I don't have any experience with Maven. Any help would be much appreciated.

**Comment by fracpete** [comment]
The `pom.xml` structure is explained [here](https://maven.apache.org/pom.html).

But, you don't need to use Maven as build tool. You can also just download the relevant jar artifacts from [Maven Central](http://search.maven.org/) and include them in your project.  But in that case, you need to manage all the dependencies yourself.

Click [here](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22multisearch-weka-package%22) to list all multisearch releases.

**Comment by ghost** [comment]
Thank you for the quick reply. I will let you know if I succeed.

**Comment by ghost** [comment]
I've already compiled it and build the jar file. What to do next?
WEKA package manager is reporting, "unrecognised as a URL or zip archive"

I apologise If am bothering you.

**Comment by fracpete** [comment]
You didn't mention that you want to generate a Weka package. Unless you have modified the code, you can simply download a release zip file from the _releases_ sub-tab (in the _Code_ tab). If you've modified the code, however, see the `RELEASE.md` file, section _Weka package_ for instructions on how to create a Weka package.

**Comment by ghost** [comment]
Its working now. Thanks.
